version: '3'
services:

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: tf-mysql:v1.0

  react-app:
    container_name: react-app
    build:
      dockerfile: Dockerfile
      args:
        - ADDRESS=172.23.253.92:31000
    image: tf-react-app:v1.0

  spring-boot-app:
    container_name: spring-boot-app
    build:
      dockerfile: Dockerfile
      context: ./spring-boot-app
    image: tf-spring-boot-app:v1.1
    environment: 
      ALLOWED_ORIGIN: "http://172.23.253.92:32000"
    depends_on:
      - mysql
    
  #default-response-app:
  #  container_name: default-response-app
  #  build:
  #    dockerfile: Dockerfile
  #    context: ./default-response-app
  #  image: tf-default-response-app:v1.0

