version: '3'
services:

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: tf-mysql:v1.0

  react-app:
    container_name: react-app
    build:
      dockerfile: Dockerfile
    image: tf-react-app:v1.6
    environment:
      ADDRESS: "http://172.23.246.168:31000"

  spring-boot-app:
    container_name: spring-boot-app
    build:
      dockerfile: Dockerfile
      context: ./spring-boot-app
    image: tf-spring-boot-app:v1.2
    environment: 
      ALLOWED_ORIGIN: "http://172.23.246.168:32000"
    
  default-response-app:
    container_name: default-response-app
    build:
      dockerfile: Dockerfile
      context: ./default-response-app
    image: tf-default-response-app:v1.0

