version: '3'
services:

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: xtf-postgres
    ports:
      - "127.0.0.1:5432:5432"

  react-app:
    container_name: react-app
    build:
      dockerfile: Dockerfile
    image: xtf-react-app
    ports:
      - "3000:3000"
  
  spring-boot-app:
    container_name: spring-boot-app
    build:
      dockerfile: Dockerfile
      context: ./spring-boot-app
    image: xtf-spring-boot-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: "postgres"
    depends_on:
      - postgres
