version: '3'
services:

  postgres:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: tf-mysql:k8s

  react-app:
    container_name: react-app
    build:
      dockerfile: Dockerfile
    image: tf-react-app:k8s
    environment:
      REACT_APP_API_BASE_URL: "http://192.168.49.2:32000"

  spring-boot-app:
    container_name: spring-boot-app
    build:
      dockerfile: Dockerfile
      context: ./spring-boot-app
    image: tf-spring-boot-app:k8s
