version: '3'
services:

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: tf-mysql:test
    ports:
      - "127.0.0.1:3306:3306"

  react-app:
    container_name: react-app
    build:
      dockerfile: Dockerfile
    image: tf-react-app:test
    ports:
      - "3000:3000"
      args:
        -ADDRESS=localhost:8080

  spring-boot-app:
    container_name: spring-boot-app
    build:
      dockerfile: Dockerfile
      context: ./spring-boot-app
    image: tf-spring-boot-app:test
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: "mysql"
    depends_on:
      - mysql
