version: '3'
services:
  greetings_pgdb:
    container_name: greetings_pgdb
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5432:5432"

  react-app:
    container_name: react-app
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - spring-boot-app
  
  spring-boot-app:
    container_name: spring-boot-app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PG_IMAGE: "greetings_pgdb"
    depends_on:
      - greetings_pgdb
