version: '3'
services:

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: tf-mysql:v1.1

  react-app:
    container_name: react-app
    build:
      dockerfile: Dockerfile
      args:
        - ADDRESS=127.0.0.1:55489
    image: tf-react-app:v1.1

  spring-boot-app:
    container_name: spring-boot-app
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
      context: ./spring-boot-app
    environment: 
      ALLOWED_ORIGIN: http://127.0.0.1:55285
    image: tf-spring-boot-app:v2.3
