openapi: 3.0.3
info:
  title: Hello World API
  version: 1.0.0

components:
  schemas:
    Greeting:
      type: object
      properties:
        message:
          type: string

    Greetings:
      type: object
      properties:
        greetings:
          type: array
          items:
            $ref: '#/components/schemas/Greeting'

paths:

  /greetings/all:
    get:
      summary: Get all messages
      description: Returns a list of messages.
      operationId: getGreetings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greetings'
      tags:
        - Greetings
