apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: app.local
    http:
      paths:
      - path: /fe
        pathType: Prefix
        backend:
          service:
            name: react-app-service
            port:
              number: 3000
      - path: /be
        pathType: Prefix
        backend:
          service:
            name: spring-boot-app-service
            port:
              number: 8080
