openapi: 3.0.3
info:
  title: Food Rating API
  version: 1.0.0

components:

  schemas:
    Greeting:
      type: object
      properties:
        message:
          type: string

    Greetings:
      type: object
      properties:
        greetings:
          type: array
          items:
            $ref: '#/components/schemas/Greeting'

    Food:
      type: object
      properties:
        name:
          type: string
        rating:
          type: number
          maximum: 10
          minimum: 1

    Foods:
      type: object
      properties:
        foods:
          type: array
          items:
            $ref: '#/components/schemas/Food'

paths:

  /foods/all:
    get:
      summary: Get all foods
      description: Returns a list of foods.
      operationId: getFoods
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foods'
      tags:
        - Foods

  /foods/add:
    post:
      summary: Add a new food
      description: Adds a food to the database.
      operationId: addFood
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Food'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Food'
      tags:
        - Foods

  /greetings/all:
    get:
      summary: Get all messages
      description: Returns a list of messages.
      operationId: getGreetings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greetings'
      tags:
        - Greetings

servers:
  - url: http://{address}
    variables:
      address:
        default: localhost:8080
        description: The current environment
